server:
  port: 8090
#配置数据源
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myhib??useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
jpa:
  hibernate:
    ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect